name: Scrape calendário e publicar dados

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 10 * * *"   # 10:00 UTC = 07:00 BRT (sem DST)
  push:
    paths:
      - "scraper/**"
      - ".github/workflows/scrape.yml"
      - "requirements.txt"

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar scraper
        run: |
          python scraper/scrape_calendar.py

      - name: Commit automático dos dados
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/calendario_residencia.json data/calendario_residencia.csv data/meta.json || true
          git commit -m "chore(data): atualizar calendário e meta.json" || echo "Nada para commitar"
          git push
